cadena=input("Ingrese una cadena de caracteres:")
print("Los dos primeros caracteres")
print(cadena[:2])
print("Los dos ultimos caracteres")
print(cadena[len(cadena)-2:])
print("Todos los caracteres menos el primero y el ultimo")
print(cadena[1:len(cadena)-1])
